---
title: "TWIN Notebook"
output: html_notebook
---
# Ref: 
# https://www.cdc.gov/growthcharts/html_charts/wtageinf.htm
# https://academic.oup.com/qje/article-abstract/120/3/1031/1841462
# https://github.com/AMLab-Amsterdam/CEVAE/blob/master/datasets/TWINS/ReadmeTwins
# https://github.com/rguo12/awesome-causality-data
Loading

```{r}
TWIN_Y<-read.csv(file="twin_pairs_Y_3years_samesex.csv")
TWIN_W<-read.csv(file="twin_pairs_T_3years_samesex.csv")
n<-dim(TWIN_Y)[1]
ths<-1000
#1:w<=ths both, 2:w<=ths one, 3: w<=ths none, 4:die both, 5: die one, 6: die none 
TWINmat<-matrix(0,nrow=n,ncol=2)
```
Fill matrix
```{r}
for(i in seq(n))
{
  flag1=flag2=0
  if(TWIN_W[i,2]<=ths)
    flag1<-1
  if(TWIN_W[i,3]<=ths)
    flag2<-1
  #TWINmat[i,1]<- flag1 & flag2
  #TWINmat[i,2]<- xor(flag1 , flag2)
  #TWINmat[i,3]<- !flag1 & !flag2
  
  #TWINmat[i,4]<- TWIN_Y[i,2] & TWIN_Y[i,3]
  #TWINmat[i,5]<- xor(TWIN_Y[i,2] , TWIN_Y[i,3])
  #TWINmat[i,6]<- !TWIN_Y[i,2] & !TWIN_Y[i,3]
  
  TWINmat[i,1]<- flag1 | flag2
  TWINmat[i,2]<- TWIN_Y[i,2] & TWIN_Y[i,3]
}
```
#save
```{r}
save(TWINmat,res,resC,file="TWINres.Rdata")
```
# analyze
```{r}
library(devtools)
devtools::document()
library(BiCausality)
confNetFunc<-function(mat,IndpThs=0.1)
{
  d<-dim(mat)[2]
  confNet<-matrix(0,nrow=d,ncol=d)
  D<-VecAlignment(mat)
  confValMat<-matrix(0,nrow=d,ncol=d)
  #===
  for(i in seq(d-1))
    for(j in seq(i+1,d))
    {
      z<-numeric(d)-1
      y<-numeric(d)-1
      y[j]<-c(1)
      z[i]<-c(1)
      a1<-CondProb(D,y=y,z=z)$condP # conf(y|z)
      b1<-CondProb(D,y=z,z=y)$condP # conf(z|y) 
      confValMat[i,j]<-a1
      confValMat[j,i]<-b1
      if((a1-b1)>0 && a1>=IndpThs)
        confNet[i,j]<-1
      else if((b1-a1)>0 && b1>= IndpThs)
        confNet[j,i]<-1
      else
        confNet[i,j]<-0
    }
  return(list(confNet=confNet,confValMat=confValMat) )
}

resC<-BiCausality::CausalGraphInferMainFunc(mat = TWINmat,CausalThs=0.1,IndpThs=.01)
resC$CausalGRes$Ehat # proposed method

res<-confNetFunc(TWINmat)
```

