---
title: "TPMap Data Preparation Notebook"
output: html_notebook
---

Edit: 07/24/2020 TKDD REV2

```{r}
#pvData <- read.csv(file="tpmap61.prov40.raw_ind.csv", header=TRUE, sep=",")
pvData <- read.csv(file="tpmap61.prov50.raw_ind.combined.csv", header=TRUE, sep=",")
```

getClsLayer
```{r}
getClsLayerFromTumbolID<-function(tumbol_ID,village_ID)
{
  provinceList <- unique(floor(pvData$tumbol_ID/10000) )
  amphoreList <- unique(floor(pvData$tumbol_ID/100) )
  tambolList <-unique(tumbol_ID)
  villageList<-village_ID
  
  N<-length(tumbol_ID)
  clsLayer<-matrix(1,N,5)
  
  clsLayer[,2]<-floor(pvData$tumbol_ID/10000) # province
  clsLayer[,3]<-(floor(pvData$tumbol_ID/100) ) #amphoreList
  clsLayer[,4]<-tumbol_ID #tambolList
  clsLayer[,5]<-village_ID
  return(list("clsLayer"=clsLayer))
}

as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}
```

tt

```{r}
# Load data
#Y<-as.numeric(pvData$col_22_1_6)  # average income col_22_1_6
X<-cbind(pvData$indicator1,pvData$indicator2,pvData$indicator3,pvData$indicator4,pvData$indicator5,pvData$indicator6,pvData$indicator7,pvData$indicator8,pvData$indicator9,pvData$indicator10)
X<-cbind(X,pvData$indicator11,pvData$indicator12,pvData$indicator13,pvData$indicator14,pvData$indicator15,pvData$indicator16,pvData$indicator17,pvData$indicator18,pvData$indicator19,pvData$indicator20)

X<-cbind(X,pvData$indicator21,pvData$indicator22,pvData$indicator23,pvData$indicator24,pvData$indicator25,pvData$indicator26,pvData$indicator27,pvData$indicator28,pvData$indicator29,pvData$indicator30,pvData$indicator31)

X[X==0]=NA
X[X==-1]=0
X[X==1]=1

clsLayer<- getClsLayerFromTumbolID(pvData$tumbol_ID,pvData$village_ID)$clsLayer

DataTProv50<-list()

#filterOutvec<-!is.na(Y)

DataTProv50$X<-X#[filterOutvec,]
#DataTProv40$Y<-as.matrix(Y[filterOutvec])
DataTProv50$clsLayer<-clsLayer#[filterOutvec,]
```

ddd
```{r}
DataTProv50$P<-DataTProv50$X
DataTProv50$P[DataTProv50$P==1]=2
DataTProv50$P[is.na(DataTProv50$P)]=2
DataTProv50$P[DataTProv50$P==0]=1
DataTProv50$P[DataTProv50$P==2]=0

DataTProv40$P<-DataTProv40$X
DataTProv40$P[DataTProv40$P==1]=2
DataTProv40$P[is.na(DataTProv40$P)]=2
DataTProv40$P[DataTProv40$P==0]=1
DataTProv40$P[DataTProv40$P==2]=0
```

Load village name

```{r}
library("stringi")
villageData <- read.csv(file="50.village_name.csv", header=TRUE, sep=",")
stri_enc_toutf8("111")

```
 Searh for VillageNamefromID
 
```{r}
VillageNamefromID<-function(villageDataPara,targetID)
{
  A<-1:length(villageDataPara$village_ID)
  inx<-A[villageDataPara$village_ID == targetID]
  villageName<-as.character(villageDataPara$village_name[inx])
  return(list("villageName"=villageName))
}
```
 
```{r}
targetID=4006060801
VillageNamefromID(villageData,targetID)$villageName
```
#Data distribution
```{r}
#barplot(table(DataT$X),xlab="Value",ylab="Frequency")
barplot(table(DataT$Y),xlab="Value",ylab="Frequency")
```

